### ISSUE TITLE
Add some sort of a loading indicator to charts

### ISSUE THREAD

**Issue by iros** [bocoup/mlab-vis-client#68]
When fetching lots of data, it might take a bit longer for the charts to update. We should have a visual indicator of this for the user so that they don't think things are broken.

**Comment by pbeshai** [comment]
To be clear, there is already a loading indicator - it fades out while loading. This may be problematic since sometimes requests take forever (at least today) and it currently waits until all data is fetched before fading back in. Perhaps if not loaded at all it is faded out with spinner. If partially loaded, no longer faded out but keep spinner until completely loaded.
